#!/usr/bin/env bash
# dev-profile-retire-legacy-hooks: hooks left by retired managers are renamed
# aside, git-lfs and unknown hooks stay, and a second run changes nothing.
# Usage: retire-legacy-hooks-fixture.sh <generated-dir>
set -euo pipefail
export HK=0 # no global git hooks inside the fixture repos

out="${1:?usage: retire-legacy-hooks-fixture.sh <generated-dir>}"
work="$(cd "$(mktemp -d)" && pwd -P)"
trap 'rm -rf "${work}"' EXIT
retire="${out}/bin/dev-profile-retire-legacy-hooks"
aside=".retired-by-dev-profile"

fail() {
	echo "FAIL retire-legacy-hooks fixture: $*" >&2
	exit 1
}

repo="${work}/repo"
git init -q "${repo}"
hooks="${repo}/.git/hooks"
printf '#!/bin/sh\ncall_lefthook run "pre-commit" "$@"\n' >"${hooks}/pre-commit"
printf '#!/bin/sh\n# managed by zq\nzq hook pre-push\n' >"${hooks}/pre-push"
printf '#!/bin/sh\ncommand -v git-lfs >/dev/null || exit 2\ngit lfs post-checkout "$@"\n' >"${hooks}/post-checkout"
printf '#!/bin/sh\necho my own hook\n' >"${hooks}/commit-msg"
printf '#!/bin/sh\n# yorkie 2.0.0\nexec yorkie-runner\n' >"${hooks}/prepare-commit-msg"
printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n' >"${hooks}/post-merge"
chmod +x "${hooks}"/*

(cd "${repo}" && "${retire}" --check) >"${work}/check.txt" 2>&1 || fail "--check must exit 0"
grep -Fq "pre-commit is a retired lefthook hook" "${work}/check.txt" || fail "--check must name the lefthook hook"
[[ -f "${hooks}/pre-commit" ]] || fail "--check must rename nothing"

"${retire}" "${repo}" >"${work}/first.txt" || fail "first run failed"
for hook in pre-commit pre-push prepare-commit-msg post-merge; do
	[[ ! -e "${hooks}/${hook}" && -f "${hooks}/${hook}${aside}" ]] || fail "${hook} must be renamed to ${hook}${aside}"
done
[[ -x "${hooks}/pre-commit${aside}" ]] || fail "a renamed hook keeps its content and mode"
for hook in post-checkout commit-msg; do
	[[ -f "${hooks}/${hook}" && ! -e "${hooks}/${hook}${aside}" ]] || fail "${hook} must stay"
done
[[ "$(wc -l <"${work}/first.txt" | tr -d ' ')" == 4 ]] || fail "first run must print the four renames"

"${retire}" "${repo}" >"${work}/second.txt" || fail "second run failed"
[[ ! -s "${work}/second.txt" ]] || fail "second run must rename and print nothing"
(cd "${repo}" && "${retire}" --check) >"${work}/check2.txt" 2>&1
[[ ! -s "${work}/check2.txt" ]] || fail "--check must be silent once healed"

# A manager that rewrites its hook later is retired again without losing the first copy.
printf '#!/bin/sh\ncall_lefthook run "pre-commit" "$@"\n' >"${hooks}/pre-commit"
"${retire}" "${repo}" >/dev/null
[[ -f "${hooks}/pre-commit${aside}" && -f "${hooks}/pre-commit${aside}.1" ]] || fail "a second retirement must keep both copies"

# A linked worktree shares the main repo's hooks.
git -C "${repo}" -c user.name=t -c user.email=t@example.com -c commit.gpgsign=false commit -q --allow-empty -m init
git -C "${repo}" worktree add -q "${work}/linked" -b linked
printf '#!/bin/sh\ncall_lefthook run "pre-push" "$@"\n' >"${hooks}/pre-push"
(cd "${work}/linked" && "${retire}") >/dev/null
[[ ! -e "${hooks}/pre-push" ]] || fail "run from a linked worktree must retire the shared hook"

echo "retire-legacy-hooks fixture ok"
